Bike data / Feature Engineering

In [14]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("../data/bike.csv")
df.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  str
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(3), int64(8), str(1)
memory usage: 1020.7 KB

In [4]:
df.isna().sum()

datetime      0
season        0
holiday       0
workingday    0
weather       0
temp          0
atemp         0
humidity      0
windspeed     0
casual        0
registered    0
count         0
dtype: int64

In [5]:
df.describe()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
count,10886.000000,10886.000000,10886.000000,10886.000000,10886.00000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000
mean,2.506614,0.028569,0.680875,1.418427,20.23086,23.655084,61.886460,12.799395,36.021955,155.552177,191.574132
std,1.116174,0.166599,0.466159,0.633839,7.79159,8.474601,19.245033,8.164537,49.960477,151.039033,181.144454
min,1.000000,0.000000,0.000000,1.000000,0.82000,0.760000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,0.000000,1.000000,13.94000,16.665000,47.000000,7.001500,4.000000,36.000000,42.000000
50%,3.000000,0.000000,1.000000,1.000000,20.50000,24.240000,62.000000,12.998000,17.000000,118.000000,145.000000
75%,4.000000,0.000000,1.000000,2.000000,26.24000,31.060000,77.000000,16.997900,49.000000,222.000000,284.000000
max,4.000000,1.000000,1.000000,4.000000,41.00000,45.455000,100.000000,56.996900,367.000000,886.000000,977.000000

Visualization

In [6]:
fig = px.histogram(df[["count", "casual", "registered"]])
fig.show()

In [7]:
fig = px.histogram(df[["temp", "atemp"]])
fig.show()

In [8]:
fig = px.histogram(df[["weather"]])
fig.show()

In [9]:
fig = px.histogram(df[["humidity"]])
fig.show()

In [10]:
fig = px.histogram(df[["windspeed"]])
fig.show()

In [18]:
corr = df.corr(numeric_only=True)
corr.style.background_gradient(cmap='coolwarm').set_caption("Correlation Matrix")

Outlier removal

In [20]:
#boxplot
fig = px.box(df[["windspeed"]])
fig.show()

In [22]:
q1= np.quantile(df["windspeed"], 0.25)
q3= np.quantile(df["windspeed"], 0.75)
iqr = q3 - q1
lower_bound = q1 -1.5 * iqr
upper_bound = q3 + 1.5 * iqr

df = df[(df["windspeed"] >= lower_bound) & (df["windspeed"] <= upper_bound)]
df.shape

(10659, 12)

In [25]:
fig = px.histogram(df[["windspeed"]])
fig.show()

In [21]:
df.shape

(10886, 12)

Transformation

In [19]:
count_transformed = np.log1p(df["count"])

fig = px.histogram(count_transformed)
fig.show()

In [26]:
casual_transformed = np.log1p(df["casual"])

fig = px.histogram(casual_transformed)
fig.show()

In [27]:
registered_transformed = np.log1p(df["registered"])

fig = px.histogram(registered_transformed)
fig.show()