Bike NN Model (Regression)

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.neural_network import MLPRegressor

In [18]:
df = pd.read_csv("../data/bike_cleaned.csv")
df.head()

,Unnamed: 0,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,...,season_sin,season_cos,month_sin,month_cos,day_sin,day_cos,day_of_week_sin,day_of_week_cos,hour_sin,hour_cos
0,0,0,0,-0.660915,-1.339086,-1.103724,0.984434,-1.652104,3,13,...,1.0,6.123234e-17,0.5,0.866025,0.324699,0.945817,-0.974928,-0.222521,0.000000,1.000000
1,1,0,0,-0.660915,-1.444375,-1.193741,0.932031,-1.652104,8,32,...,1.0,6.123234e-17,0.5,0.866025,0.324699,0.945817,-0.974928,-0.222521,0.258819,0.965926
2,2,0,0,-0.660915,-1.444375,-1.193741,0.932031,-1.652104,5,27,...,1.0,6.123234e-17,0.5,0.866025,0.324699,0.945817,-0.974928,-0.222521,0.500000,0.866025
3,3,0,0,-0.660915,-1.339086,-1.103724,0.670013,-1.652104,3,10,...,1.0,6.123234e-17,0.5,0.866025,0.324699,0.945817,-0.974928,-0.222521,0.707107,0.707107
4,4,0,0,-0.660915,-1.339086,-1.103724,0.670013,-1.652104,0,1,...,1.0,6.123234e-17,0.5,0.866025,0.324699,0.945817,-0.974928,-0.222521,0.866025,0.500000

Test/Train Split

In [19]:
x = df.drop(columns=['count', 'casual', 'registered', 'Unnamed: 0'])
y = df['count']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [20]:
x_train

,holiday,workingday,weather,temp,atemp,humidity,windspeed,season_sin,season_cos,month_sin,month_cos,day_sin,day_cos,day_of_week_sin,day_of_week_cos,hour_sin,hour_cos
6567,0,0,0.923587,-0.286194,-0.206515,1.351259,-0.442790,1.000000e+00,6.123234e-17,1.000000e+00,6.123234e-17,-3.246995e-01,0.945817,-0.781831,0.623490,1.224647e-16,-1.000000
2709,0,1,-0.660915,1.503722,1.587903,-0.011234,0.632356,-1.000000e+00,-1.836970e-16,-5.000000e-01,-8.660254e-01,9.965845e-01,-0.082579,0.781831,0.623490,-7.071068e-01,0.707107
9290,0,1,-0.660915,0.556119,0.870136,-1.164113,0.632356,-1.000000e+00,-1.836970e-16,-1.000000e+00,-1.836970e-16,-2.449294e-16,1.000000,0.974928,-0.222521,-2.588190e-01,-0.965926
4742,0,1,2.508089,0.240252,0.242385,-0.116041,0.364020,-2.449294e-16,1.000000e+00,-5.000000e-01,8.660254e-01,-9.694003e-01,0.245485,0.781831,0.623490,-2.588190e-01,-0.965926
2484,0,1,-0.660915,0.766698,0.870136,-0.797288,-0.173553,1.224647e-16,-1.000000e+00,1.224647e-16,-1.000000e+00,-9.694003e-01,0.245485,0.974928,-0.222521,5.000000e-01,-0.866025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,0,1,-0.660915,-0.496772,-0.385957,-0.640077,-0.173553,1.000000e+00,6.123234e-17,8.660254e-01,5.000000e-01,3.246995e-01,0.945817,0.974928,-0.222521,9.659258e-01,0.258819
5191,0,1,0.923587,-0.707351,-0.834858,-0.011234,0.901592,-2.449294e-16,1.000000e+00,-2.449294e-16,1.000000e+00,-9.694003e-01,0.245485,0.433884,-0.900969,7.071068e-01,-0.707107
5390,0,1,-0.660915,-1.549664,-1.462608,-0.587673,-0.845294,1.000000e+00,6.123234e-17,5.000000e-01,8.660254e-01,9.965845e-01,-0.082579,0.433884,-0.900969,2.588190e-01,0.965926
860,0,1,-0.660915,-1.444375,-1.552625,0.355591,0.364020,1.000000e+00,6.123234e-17,1.000000e+00,6.123234e-17,6.142127e-01,0.789141,0.974928,-0.222521,9.659258e-01,0.258819
7270,0,1,-0.660915,0.029673,0.062351,-0.587673,2.110906,1.224647e-16,-1.000000e+00,5.000000e-01,-8.660254e-01,-1.645946e-01,-0.986361,0.433884,-0.900969,5.000000e-01,-0.866025

In [21]:
y_train

6567    503
2709    245
9290    289
4742    153
2484    135
       ...
5734     18
5191    280
5390      5
860       5
7270    154
Name: count, Length: 8527, dtype: int64

In [22]:
#Scaling y_train
target_scaler = StandardScaler()
y_train_scaled = target_scaler.fit_transform(y_train.values.reshape(-1, 1))

In [23]:
#Load MLPRegressor
model = MLPRegressor(hidden_layer_sizes=(100, 50), activation='relu', solver='adam', 
                            max_iter=1000, random_state=42, verbose=True, early_stopping=True, 
                            n_iter_no_change=100)
#fit the model
model.fit(x_train, y_train_scaled)

c:\Users\monat\anaconda3\envs\ai\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1771: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Iteration 1, loss = 0.32643316
Validation score: 0.464519
Iteration 2, loss = 0.24272152
Validation score: 0.539504
Iteration 3, loss = 0.21167186
Validation score: 0.590997
Iteration 4, loss = 0.18965989
Validation score: 0.624835
Iteration 5, loss = 0.16968505
Validation score: 0.669188
Iteration 6, loss = 0.15023639
Validation score: 0.700274
Iteration 7, loss = 0.13414343
Validation score: 0.730175
Iteration 8, loss = 0.11997440
Validation score: 0.747006
Iteration 9, loss = 0.11062833
Validation score: 0.770894
Iteration 10, loss = 0.10234250
Validation score: 0.781513
Iteration 11, loss = 0.09544862
Validation score: 0.789621
Iteration 12, loss = 0.09121160
Validation score: 0.797305
Iteration 13, loss = 0.08805884
Validation score: 0.809145
Iteration 14, loss = 0.08443636
Validation score: 0.808555
Iteration 15, loss = 0.08163349
Validation score: 0.814753
Iteration 16, loss = 0.07933622
Validation score: 0.823551
Iteration 17, loss = 0.07589933
Validation score: 0.822613
Iteration 18, loss = 0.07425118
Validation score: 0.828477
Iteration 19, loss = 0.07219697
Validation score: 0.833897
Iteration 20, loss = 0.07028433
Validation score: 0.834079
Iteration 21, loss = 0.06893365
Validation score: 0.840311
Iteration 22, loss = 0.06718025
Validation score: 0.839605
Iteration 23, loss = 0.06605637
Validation score: 0.843642
Iteration 24, loss = 0.06409235
Validation score: 0.844356
Iteration 25, loss = 0.06368457
Validation score: 0.849606
Iteration 26, loss = 0.06165723
Validation score: 0.848520
Iteration 27, loss = 0.06089635
Validation score: 0.847724
Iteration 28, loss = 0.05904129
Validation score: 0.850716
Iteration 29, loss = 0.05842857
Validation score: 0.856063
Iteration 30, loss = 0.05661432
Validation score: 0.853191
Iteration 31, loss = 0.05609190
Validation score: 0.859544
Iteration 32, loss = 0.05532521
Validation score: 0.860571
Iteration 33, loss = 0.05384197
Validation score: 0.860403
Iteration 34, loss = 0.05285767
Validation score: 0.860454
Iteration 35, loss = 0.05174090
Validation score: 0.866889
Iteration 36, loss = 0.05126434
Validation score: 0.866212
Iteration 37, loss = 0.05072106
Validation score: 0.866505
Iteration 38, loss = 0.04997794
Validation score: 0.869849
Iteration 39, loss = 0.04901885
Validation score: 0.865325
Iteration 40, loss = 0.04765955
Validation score: 0.871833
Iteration 41, loss = 0.04759932
Validation score: 0.871456
Iteration 42, loss = 0.04668304
Validation score: 0.871424
Iteration 43, loss = 0.04578307
Validation score: 0.874840
Iteration 44, loss = 0.04590833
Validation score: 0.877146
Iteration 45, loss = 0.04500148
Validation score: 0.872153
Iteration 46, loss = 0.04539784
Validation score: 0.866517
Iteration 47, loss = 0.04432235
Validation score: 0.877334
Iteration 48, loss = 0.04341132
Validation score: 0.878473
Iteration 49, loss = 0.04224443
Validation score: 0.878939
Iteration 50, loss = 0.04171874
Validation score: 0.870918
Iteration 51, loss = 0.04172767
Validation score: 0.876372
Iteration 52, loss = 0.04083053
Validation score: 0.881386
Iteration 53, loss = 0.03993444
Validation score: 0.879573
Iteration 54, loss = 0.04084970
Validation score: 0.878649
Iteration 55, loss = 0.03902406
Validation score: 0.878721
Iteration 56, loss = 0.03951537
Validation score: 0.882723
Iteration 57, loss = 0.03960171
Validation score: 0.883013
Iteration 58, loss = 0.03892088
Validation score: 0.883609
Iteration 59, loss = 0.03778566
Validation score: 0.884278
Iteration 60, loss = 0.03671172
Validation score: 0.886241
Iteration 61, loss = 0.03699137
Validation score: 0.886572
Iteration 62, loss = 0.03692495
Validation score: 0.886154
Iteration 63, loss = 0.03558246
Validation score: 0.886801
Iteration 64, loss = 0.03577532
Validation score: 0.886849
Iteration 65, loss = 0.03531481
Validation score: 0.887370
Iteration 66, loss = 0.03669363
Validation score: 0.887780
Iteration 67, loss = 0.03443670
Validation score: 0.890029
Iteration 68, loss = 0.03398855
Validation score: 0.888718
Iteration 69, loss = 0.03411414
Validation score: 0.886085
Iteration 70, loss = 0.03282761
Validation score: 0.890526
Iteration 71, loss = 0.03282388
Validation score: 0.888776
Iteration 72, loss = 0.03292023
Validation score: 0.880025
Iteration 73, loss = 0.03295352
Validation score: 0.889273
Iteration 74, loss = 0.03222032
Validation score: 0.886341
Iteration 75, loss = 0.03322514
Validation score: 0.885738
Iteration 76, loss = 0.03275678
Validation score: 0.888543
Iteration 77, loss = 0.03140320
Validation score: 0.886470
Iteration 78, loss = 0.03257628
Validation score: 0.887548
Iteration 79, loss = 0.03131479
Validation score: 0.886478
Iteration 80, loss = 0.03142890
Validation score: 0.884564
Iteration 81, loss = 0.03131465
Validation score: 0.891657
Iteration 82, loss = 0.02981711
Validation score: 0.890602
Iteration 83, loss = 0.03004851
Validation score: 0.893583
Iteration 84, loss = 0.02955442
Validation score: 0.891927
Iteration 85, loss = 0.02951238
Validation score: 0.891008
Iteration 86, loss = 0.02962741
Validation score: 0.889757
Iteration 87, loss = 0.03074513
Validation score: 0.895542
Iteration 88, loss = 0.02924025
Validation score: 0.893469
Iteration 89, loss = 0.02844809
Validation score: 0.893492
Iteration 90, loss = 0.02906657
Validation score: 0.888127
Iteration 91, loss = 0.02885853
Validation score: 0.889086
Iteration 92, loss = 0.02813685
Validation score: 0.892497
Iteration 93, loss = 0.02779265
Validation score: 0.891116
Iteration 94, loss = 0.02755176
Validation score: 0.894799
Iteration 95, loss = 0.02742147
Validation score: 0.892412
Iteration 96, loss = 0.02763323
Validation score: 0.891334
Iteration 97, loss = 0.02723233
Validation score: 0.895166
Iteration 98, loss = 0.02641089
Validation score: 0.894184
Iteration 99, loss = 0.02654035
Validation score: 0.894931
Iteration 100, loss = 0.02668868
Validation score: 0.895553
Iteration 101, loss = 0.02628208
Validation score: 0.896670
Iteration 102, loss = 0.02678031
Validation score: 0.893981
Iteration 103, loss = 0.02635896
Validation score: 0.893473
Iteration 104, loss = 0.02628181
Validation score: 0.892337
Iteration 105, loss = 0.02610544
Validation score: 0.893731
Iteration 106, loss = 0.02543609
Validation score: 0.894807
Iteration 107, loss = 0.02590522
Validation score: 0.893203
Iteration 108, loss = 0.02672408
Validation score: 0.895733
Iteration 109, loss = 0.02504833
Validation score: 0.894458
Iteration 110, loss = 0.02489765
Validation score: 0.896774
Iteration 111, loss = 0.02477374
Validation score: 0.892387
Iteration 112, loss = 0.02487218
Validation score: 0.896259
Iteration 113, loss = 0.02586159
Validation score: 0.889930
Iteration 114, loss = 0.02490441
Validation score: 0.894890
Iteration 115, loss = 0.02392301
Validation score: 0.896410
Iteration 116, loss = 0.02432208
Validation score: 0.895414
Iteration 117, loss = 0.02352339
Validation score: 0.890431
Iteration 118, loss = 0.02422397
Validation score: 0.893559
Iteration 119, loss = 0.02396706
Validation score: 0.896757
Iteration 120, loss = 0.02311257
Validation score: 0.895434
Iteration 121, loss = 0.02304132
Validation score: 0.896747
Iteration 122, loss = 0.02321251
Validation score: 0.888564
Iteration 123, loss = 0.02320405
Validation score: 0.895709
Iteration 124, loss = 0.02320246
Validation score: 0.895298
Iteration 125, loss = 0.02345629
Validation score: 0.894640
Iteration 126, loss = 0.02232816
Validation score: 0.895554
Iteration 127, loss = 0.02316547
Validation score: 0.892005
Iteration 128, loss = 0.02223589
Validation score: 0.895131
Iteration 129, loss = 0.02228687
Validation score: 0.895526
Iteration 130, loss = 0.02237645
Validation score: 0.893941
Iteration 131, loss = 0.02204496
Validation score: 0.898085
Iteration 132, loss = 0.02240183
Validation score: 0.894948
Iteration 133, loss = 0.02193749
Validation score: 0.892200
Iteration 134, loss = 0.02190273
Validation score: 0.895255
Iteration 135, loss = 0.02114926
Validation score: 0.893008
Iteration 136, loss = 0.02119645
Validation score: 0.896296
Iteration 137, loss = 0.02210835
Validation score: 0.892735
Iteration 138, loss = 0.02109627
Validation score: 0.893446
Iteration 139, loss = 0.02144828
Validation score: 0.896686
Iteration 140, loss = 0.02104352
Validation score: 0.892213
Iteration 141, loss = 0.02089474
Validation score: 0.895749
Iteration 142, loss = 0.02055296
Validation score: 0.895779
Iteration 143, loss = 0.02164826
Validation score: 0.890716
Iteration 144, loss = 0.02169310
Validation score: 0.893978
Iteration 145, loss = 0.02090731
Validation score: 0.890119
Iteration 146, loss = 0.02069247
Validation score: 0.896378
Iteration 147, loss = 0.02081549
Validation score: 0.894290
Iteration 148, loss = 0.02023138
Validation score: 0.891621
Iteration 149, loss = 0.02023009
Validation score: 0.893823
Iteration 150, loss = 0.01974130
Validation score: 0.895940
Iteration 151, loss = 0.02027494
Validation score: 0.893959
Iteration 152, loss = 0.01993013
Validation score: 0.895940
Iteration 153, loss = 0.01984265
Validation score: 0.890426
Iteration 154, loss = 0.01958769
Validation score: 0.895817
Iteration 155, loss = 0.01951706
Validation score: 0.890262
Iteration 156, loss = 0.01981393
Validation score: 0.895585
Iteration 157, loss = 0.01917647
Validation score: 0.889072
Iteration 158, loss = 0.02110540
Validation score: 0.893380
Iteration 159, loss = 0.01895671
Validation score: 0.895264
Iteration 160, loss = 0.01868558
Validation score: 0.894944
Iteration 161, loss = 0.01895755
Validation score: 0.896330
Iteration 162, loss = 0.01945796
Validation score: 0.894359
Iteration 163, loss = 0.01961028
Validation score: 0.895402
Iteration 164, loss = 0.01907252
Validation score: 0.893197
Iteration 165, loss = 0.01912362
Validation score: 0.892068
Iteration 166, loss = 0.01843144
Validation score: 0.893857
Iteration 167, loss = 0.01876881
Validation score: 0.894866
Iteration 168, loss = 0.01870122
Validation score: 0.895157
Iteration 169, loss = 0.01797655
Validation score: 0.895542
Iteration 170, loss = 0.01819723
Validation score: 0.898596
Iteration 171, loss = 0.01799486
Validation score: 0.893218
Iteration 172, loss = 0.01794264
Validation score: 0.894742
Iteration 173, loss = 0.01851928
Validation score: 0.893543
Iteration 174, loss = 0.01834236
Validation score: 0.894449
Iteration 175, loss = 0.01817096
Validation score: 0.895418
Iteration 176, loss = 0.01832555
Validation score: 0.893650
Iteration 177, loss = 0.01783062
Validation score: 0.893393
Iteration 178, loss = 0.01811671
Validation score: 0.893929
Iteration 179, loss = 0.01781703
Validation score: 0.893966
Iteration 180, loss = 0.01810042
Validation score: 0.892166
Iteration 181, loss = 0.01835025
Validation score: 0.893505
Iteration 182, loss = 0.01749671
Validation score: 0.894913
Iteration 183, loss = 0.01754552
Validation score: 0.896292
Iteration 184, loss = 0.01734375
Validation score: 0.895434
Iteration 185, loss = 0.01737803
Validation score: 0.895030
Iteration 186, loss = 0.01734555
Validation score: 0.896817
Iteration 187, loss = 0.01719127
Validation score: 0.892177
Iteration 188, loss = 0.01722534
Validation score: 0.897387
Iteration 189, loss = 0.01689740
Validation score: 0.895878
Iteration 190, loss = 0.01671132
Validation score: 0.896551
Iteration 191, loss = 0.01703621
Validation score: 0.891972
Iteration 192, loss = 0.01694947
Validation score: 0.897194
Iteration 193, loss = 0.01734470
Validation score: 0.892848
Iteration 194, loss = 0.01712803
Validation score: 0.894469
Iteration 195, loss = 0.01719746
Validation score: 0.896405
Iteration 196, loss = 0.01642513
Validation score: 0.898544
Iteration 197, loss = 0.01680832
Validation score: 0.898289
Iteration 198, loss = 0.01635039
Validation score: 0.890979
Iteration 199, loss = 0.01685264
Validation score: 0.894831
Iteration 200, loss = 0.01621501
Validation score: 0.897412
Iteration 201, loss = 0.01736355
Validation score: 0.896954
Iteration 202, loss = 0.01717172
Validation score: 0.897032
Iteration 203, loss = 0.01680740
Validation score: 0.896030
Iteration 204, loss = 0.01627271
Validation score: 0.895051
Iteration 205, loss = 0.01618338
Validation score: 0.898821
Iteration 206, loss = 0.01649489
Validation score: 0.890629
Iteration 207, loss = 0.01706625
Validation score: 0.895034
Iteration 208, loss = 0.01591532
Validation score: 0.898312
Iteration 209, loss = 0.01550083
Validation score: 0.892221
Iteration 210, loss = 0.01691465
Validation score: 0.894302
Iteration 211, loss = 0.01644433
Validation score: 0.894455
Iteration 212, loss = 0.01614900
Validation score: 0.897592
Iteration 213, loss = 0.01531487
Validation score: 0.891645
Iteration 214, loss = 0.01660255
Validation score: 0.895067
Iteration 215, loss = 0.01606886
Validation score: 0.897063
Iteration 216, loss = 0.01646053
Validation score: 0.897632
Iteration 217, loss = 0.01521201
Validation score: 0.896606
Iteration 218, loss = 0.01528685
Validation score: 0.896169
Iteration 219, loss = 0.01633508
Validation score: 0.894600
Iteration 220, loss = 0.01635525
Validation score: 0.894294
Iteration 221, loss = 0.01584249
Validation score: 0.897406
Iteration 222, loss = 0.01505688
Validation score: 0.892733
Iteration 223, loss = 0.01566997
Validation score: 0.899307
Iteration 224, loss = 0.01680143
Validation score: 0.893700
Iteration 225, loss = 0.01596916
Validation score: 0.898888
Iteration 226, loss = 0.01534630
Validation score: 0.897316
Iteration 227, loss = 0.01576208
Validation score: 0.893911
Iteration 228, loss = 0.01490848
Validation score: 0.895315
Iteration 229, loss = 0.01522343
Validation score: 0.895391
Iteration 230, loss = 0.01464182
Validation score: 0.895903
Iteration 231, loss = 0.01531154
Validation score: 0.894740
Iteration 232, loss = 0.01540796
Validation score: 0.896900
Iteration 233, loss = 0.01466215
Validation score: 0.895275
Iteration 234, loss = 0.01484955
Validation score: 0.896106
Iteration 235, loss = 0.01512578
Validation score: 0.896613
Iteration 236, loss = 0.01521751
Validation score: 0.897254
Iteration 237, loss = 0.01454085
Validation score: 0.896826
Iteration 238, loss = 0.01423319
Validation score: 0.897208
Iteration 239, loss = 0.01445609
Validation score: 0.894242
Iteration 240, loss = 0.01522277
Validation score: 0.889749
Iteration 241, loss = 0.01550755
Validation score: 0.893013
Iteration 242, loss = 0.01502558
Validation score: 0.895488
Iteration 243, loss = 0.01438021
Validation score: 0.899511
Iteration 244, loss = 0.01459014
Validation score: 0.893608
Iteration 245, loss = 0.01485613
Validation score: 0.892590
Iteration 246, loss = 0.01420477
Validation score: 0.895881
Iteration 247, loss = 0.01427307
Validation score: 0.896272
Iteration 248, loss = 0.01437945
Validation score: 0.897441
Iteration 249, loss = 0.01459343
Validation score: 0.896204
Iteration 250, loss = 0.01388997
Validation score: 0.895146
Iteration 251, loss = 0.01450665
Validation score: 0.898678
Iteration 252, loss = 0.01395107
Validation score: 0.895815
Iteration 253, loss = 0.01432069
Validation score: 0.893012
Iteration 254, loss = 0.01425451
Validation score: 0.893195
Iteration 255, loss = 0.01401683
Validation score: 0.896449
Iteration 256, loss = 0.01391811
Validation score: 0.898832
Iteration 257, loss = 0.01371166
Validation score: 0.896685
Iteration 258, loss = 0.01404624
Validation score: 0.896821
Iteration 259, loss = 0.01422856
Validation score: 0.898554
Iteration 260, loss = 0.01499204
Validation score: 0.898410
Iteration 261, loss = 0.01443944
Validation score: 0.897122
Iteration 262, loss = 0.01407651
Validation score: 0.896127
Iteration 263, loss = 0.01385730
Validation score: 0.895543
Iteration 264, loss = 0.01372798
Validation score: 0.894678
Iteration 265, loss = 0.01379290
Validation score: 0.895051
Iteration 266, loss = 0.01406802
Validation score: 0.894635
Iteration 267, loss = 0.01385781
Validation score: 0.895093
Iteration 268, loss = 0.01347592
Validation score: 0.898160
Iteration 269, loss = 0.01370987
Validation score: 0.899302
Iteration 270, loss = 0.01382004
Validation score: 0.898072
Iteration 271, loss = 0.01360438
Validation score: 0.897743
Iteration 272, loss = 0.01387225
Validation score: 0.897373
Iteration 273, loss = 0.01349643
Validation score: 0.896891
Iteration 274, loss = 0.01318363
Validation score: 0.896978
Iteration 275, loss = 0.01354159
Validation score: 0.896172
Iteration 276, loss = 0.01361080
Validation score: 0.896697
Iteration 277, loss = 0.01441310
Validation score: 0.887100
Iteration 278, loss = 0.01414988
Validation score: 0.896976
Iteration 279, loss = 0.01356599
Validation score: 0.894246
Iteration 280, loss = 0.01324566
Validation score: 0.890784
Iteration 281, loss = 0.01390237
Validation score: 0.897534
Iteration 282, loss = 0.01351934
Validation score: 0.900586
Iteration 283, loss = 0.01277694
Validation score: 0.897824
Iteration 284, loss = 0.01346624
Validation score: 0.895164
Iteration 285, loss = 0.01276248
Validation score: 0.893677
Iteration 286, loss = 0.01345444
Validation score: 0.893588
Iteration 287, loss = 0.01292721
Validation score: 0.896563
Iteration 288, loss = 0.01269672
Validation score: 0.895813
Iteration 289, loss = 0.01277347
Validation score: 0.895895
Iteration 290, loss = 0.01296919
Validation score: 0.896634
Iteration 291, loss = 0.01382530
Validation score: 0.896988
Iteration 292, loss = 0.01285409
Validation score: 0.898306
Iteration 293, loss = 0.01277742
Validation score: 0.896519
Iteration 294, loss = 0.01288399
Validation score: 0.897833
Iteration 295, loss = 0.01271554
Validation score: 0.895441
Iteration 296, loss = 0.01259171
Validation score: 0.895004
Iteration 297, loss = 0.01313665
Validation score: 0.895303
Iteration 298, loss = 0.01282117
Validation score: 0.897290
Iteration 299, loss = 0.01311771
Validation score: 0.897033
Iteration 300, loss = 0.01285835
Validation score: 0.894539
Iteration 301, loss = 0.01267345
Validation score: 0.899096
Iteration 302, loss = 0.01269145
Validation score: 0.893200
Iteration 303, loss = 0.01361754
Validation score: 0.896875
Iteration 304, loss = 0.01286470
Validation score: 0.895096
Iteration 305, loss = 0.01266521
Validation score: 0.893153
Iteration 306, loss = 0.01241683
Validation score: 0.897972
Iteration 307, loss = 0.01261798
Validation score: 0.896721
Iteration 308, loss = 0.01262585
Validation score: 0.893405
Iteration 309, loss = 0.01311379
Validation score: 0.896045
Iteration 310, loss = 0.01212569
Validation score: 0.896950
Iteration 311, loss = 0.01213439
Validation score: 0.897723
Iteration 312, loss = 0.01199216
Validation score: 0.894680
Iteration 313, loss = 0.01219081
Validation score: 0.894931
Iteration 314, loss = 0.01201377
Validation score: 0.895914
Iteration 315, loss = 0.01244931
Validation score: 0.895071
Iteration 316, loss = 0.01211737
Validation score: 0.893616
Iteration 317, loss = 0.01238139
Validation score: 0.895946
Iteration 318, loss = 0.01278768
Validation score: 0.895229
Iteration 319, loss = 0.01232141
Validation score: 0.897140
Iteration 320, loss = 0.01272576
Validation score: 0.896837
Iteration 321, loss = 0.01219860
Validation score: 0.896758
Iteration 322, loss = 0.01286583
Validation score: 0.894190
Iteration 323, loss = 0.01267930
Validation score: 0.892883
Iteration 324, loss = 0.01276072
Validation score: 0.899829
Iteration 325, loss = 0.01257982
Validation score: 0.894710
Iteration 326, loss = 0.01238088
Validation score: 0.897246
Iteration 327, loss = 0.01175833
Validation score: 0.895459
Iteration 328, loss = 0.01214621
Validation score: 0.893352
Iteration 329, loss = 0.01169828
Validation score: 0.897413
Iteration 330, loss = 0.01213525
Validation score: 0.893830
Iteration 331, loss = 0.01222052
Validation score: 0.895466
Iteration 332, loss = 0.01218870
Validation score: 0.899888
Iteration 333, loss = 0.01197244
Validation score: 0.898326
Iteration 334, loss = 0.01176221
Validation score: 0.894865
Iteration 335, loss = 0.01233010
Validation score: 0.896601

MLPRegressor(early_stopping=True, hidden_layer_sizes=(100, 50), max_iter=1000,
             n_iter_no_change=100, random_state=42, verbose=True)